version: "3.6"
services:
    ui:
        build:
            context: ./mondongo-ui
            dockerfile: Dockerfile
        ports:
            - "81:80"
            - "8081:8080"
        networks:
            - front
    api:
        build:
            context: ./mondongo.api
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "8080:8080"
        depends_on:
            - mongo
        networks:
            - front
            - back
    mongo:
        image: "mongo:4.4.1"
        networks:
            - back
networks:
    front:
        driver: bridge
    back:
        driver: bridge