version: "3.6"
services:
    api:
        build:
            context: ./mondongo.api
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "8080:8080"
        depends_on:
            - mongo
        networks:
            - custom
    mongo:
        image: "mongo:4.4.1"
        networks:
            - custom
networks:
    custom:
        driver: bridge